# Generated by Django 4.0.4 on 2022-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='coutntry_code',
            field=models.CharField(default=91, max_length=6),
            preserve_default=False,
        ),
    ]
