# Generated by Django 4.0.4 on 2022-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_message_coutntry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
